
source 'https://rubygems.org'

ruby '2.3.1'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', ' 5.0.1' #'~> 5.0.0', '>= 5.0.0.1'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.18'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'


gem 'rails_12factor'
gem 'rack-cors', :require => 'rack/cors'
#gem 'delayed_job_active_record'
#gem 'delayed_job_web'
gem 'grape'
gem 'grape-swagger'
gem 'grape-swagger-entity'
gem 'grape-swagger-representable'
gem 'hashie-forbidden_attributes'
gem 'phantomjs'
gem 'capybara'
gem 'poltergeist'
gem 'concurrent-ruby', require: 'concurrent'
gem 'devise'
gem 'doorkeeper'
gem 'devise-doorkeeper'
gem 'delayed_job'
gem 'delayed_job_active_record'
gem 'delayed-web'
gem 'tod'
gem 'business_time'
gem 'tzip'
gem 'audited', '~> 4.3'
gem 'rails-observers', github: 'rails/rails-observers'
gem 'factory_girl_rails'
gem 'kaminari-grape'
gem 'grape-kaminari'
gem 'wine_bouncer'
gem 'grape-entity'
gem 'daemons'
gem 'staccato'
gem 'activejob-cancel'
gem 'faker'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  gem 'rspec-rails'


  gem 'listen' #, '~> 3.0.5'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'

end

group :test do
  gem 'shoulda-matchers'
  gem 'rspec-expectations'
  gem 'database_cleaner'
  gem 'rspec-json_expectations'
  gem 'rspec-activejob'
  gem 'rspec-wait'
  gem 'rspec-support'
  gem 'json_spec'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
